### ISSUE TITLE
IM TRYING TO COMPILE YOUR CODE IN VS2019 BUT IM GETTING THIS 

### ISSUE THREAD

**Issue by awipslinuxuser** [MishaTY/Misha-OS#17]
#### Other  
  
- Please explain below.

**Comment by awipslinuxuser** [comment]
cannot access a disposed object object name:
'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.
Microsft.VisualStudio.ProjectSystem.VS.Implementation,
Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]'.

**Comment by MishaTY** [comment]
Try restarting visual studio

**Comment by awipslinuxuser** [comment]
ok but when i use the close button the same error popped up but i used tasked manager to force closed it closed i get that you created the code but how would you compile it without giving that error???

**Comment by MishaTY** [comment]
It's an issue with Visual studio, not MishaOS.
