### ISSUE TITLE
Random, Unrelated Errors involving "Fonts"

### ISSUE THREAD

**Issue by sketchedgrey** [MishaTY/Misha-OS#8]
#### Choose one of the following options for an issue:
- Bug report  
  
#### Bug Report
- What were you doing when you encountered the bug? How can it be reproduced? 
I was compiling MishaOS to test out some things I have added. To reproduce the bug, try to compile MishaOS
- What should happen instead of the bug? 
MishaOS should compile normally
- What happens unexpectedly?
I get completely unrelated error to what I was doing on completely random scripts:
![image](https://user-images.githubusercontent.com/67015228/116476773-b48ab400-a849-11eb-9de2-5e1f88eb3727.png)
I was editing void Drawmouse on Mouse.cs.

**Comment by MishaTY** [comment]
To get rid of these errors, install the Cosmos devkit not the userkit.

**Comment by sketchedgrey** [comment]
OK! That should have been obvious, I guess. Thanks!

**Comment by MishaTY** [comment]
Your welcome!
